kind: pipeline
name: default

common: &common
  image: golang:alpine
  commands:
  - apk add --no-cache binutils
  - go build -v -o "webdd-${GOOS}-${GOARCH}"
  - strip "webdd-${GOOS}-${GOARCH}"

steps:
- name: build-linux-amd64
  <<: *common
  environment:
    GOOS: linux
    GOARCH: amd64

- name: build-windows-amd64
  <<: *common
  environment:
    GOOS: windows
    GOARCH: amd64

- name: test
  image: golang:alpine
  commands:
  - apk add --no-cache gcc musl-dev
  - go test -v ./...

- name: deploy
  image: plugins/s3
  settings:
    source: webdd-*
    target: "/${DRONE_REPO_NAME}"
    bucket: cicd
    access_key: cicd
    secret_key:
      from_secret: s3_key
    path_style: true
    endpoint: https://minio.toast.cafe
  when:
    branch:
    - master
    event:
    - push
